apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: valuehero-pingpong.runs.onstackit.cloud
    http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: ping-pong-client-service
            port: 
              number: 8080