---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sqlite-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ping-pong-service
  name: sqlite-pv-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M