
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${resource_name}
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: "${github_repo_url}"
    targetRevision: master
    path: ${helm_chart_path}
    helm:
      valueFiles:
      - values.yaml
